# Generated by Django 5.0.6 on 2024-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_delete_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/images/'),
        ),
    ]
