# Generated by Django 5.0.6 on 2024-06-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['position']},
        ),
    ]
