# Generated by Django 5.0.6 on 2024-06-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='external_link',
        ),
    ]
