# Generated by Django 5.0.6 on 2024-07-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_quiz_description_remove_quiz_subject_and_more'),
        ('subjects', '0003_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
