# Generated by Django 5.0.6 on 2024-06-24 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_subject'),
        ('subjects', '0003_lesson_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
            preserve_default=False,
        ),
    ]
