# Generated by Django 5.0.6 on 2024-06-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_subject_alter_quiz_subject'),
        ('subjects', '0003_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
