# Generated by Django 5.0.6 on 2024-07-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_description_quiz_subject_userquiz_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
    ]
